### ISSUE TITLE
[转型讨论][话题] 信息之难

### ISSUE THREAD

**Issue by cp4** [zoom-quiet/Noah2Ark#24]
- 转型过程中，你最希望获取的信息是什么？  
- 怎样获得想要的信息？  
- 对你帮助最大的信息是什么？  
- 转型后意料之中和意料之外的分别是什么？  
- 回头看，哪些信息你认为是早应该知道的？

**Comment by ZoomQuiet** [comment]
嗯哼, 这是对所有分享的领域性提问, 不过,应该递进哪:
- 最希望获得的信息是什么? 为什么?
- 这类信息获得后,对自己的什么行为有极大的促进?为什么?
- 这一行为对转型的成功是至关重要的嘛? 为什么?
- 回顾以及参考其它人的经历, 再决策渴望什么信息? 为什么?
