### ISSUE TITLE
[转型讨论][话题] 技能之难

### ISSUE THREAD

**Issue by cp4** [zoom-quiet/Noah2Ark#25]
- 怎样开辟第二技能？  
- 你选择新技能的依据是什么？  
- 断臂式与渐进式开辟新技能孰优孰劣？
- 年龄大了还能实现技能突围吗？  
- 稳定推进第二技能发展的实践有哪些？  
- 怎样利用人际网络推进学习？

**Comment by huzhishan** [comment]
编程，必须是编程。心理学科班出身， 很后悔本科时没好好利用网络，没好好学编程与算法。现在可苦逼了。

**Comment by ZoomQuiet** [comment]
嗯哼, 一样体系化一下:
- 如果决断新技能的自学?为什么?
- 如何检验技能 got 否?为什么?
- 技能对转型领域的进入帮助有多大? 以往经验是否能复用? 如何检验?为什么?

**Comment by alexqiao** [comment]
对怎样开辟第二技能感兴趣。 
我相信年龄大了仍有机会发展和开辟第二技能，但技能需对过往的经历有传承性。若稳定推进第二技能发展，个人实践可以在日常工作中初步尝试践行，从小事点点滴滴逐步累积。 
衍生问题：断臂式转行与渐进式的孰优孰劣。个人曾断臂一次，至今仍舔舐伤口，但也发现一些技能的传承不变性，现在个人更倾向于渐进式。
