### ISSUE TITLE
[转型讨论][话题] 金钱之难

### ISSUE THREAD

**Issue by cp4** [zoom-quiet/Noah2Ark#27]
- 知识转化为金钱的路径是什么？  
- 价值是什么，价值感是什么？
- 价值的逻辑是什么，金钱的逻辑又是什么？  
- 为什么拥有知识却没有创造价值？  
- 为什么创造了价值却不产生金钱？  
- 金钱涌动的地方一定创造了价值吗？
- 未来，价值与金钱的步调更趋一致，还是更加分裂？
## DAMA-style
- 金銭是最重要的资源嘛?为什么?如何证明?
- 以往利用金钱最成功的交易是什么?为什么?
- 以往使用金钱最失败的交易是什么?为什么?
- 获得金钱回报最稳妥的渠道是什么?为什么?
- 你最看重什么样的回报?为什么?

**Comment by cp4** [comment]
我谈谈对知识变现这件事的想法，回答上面的部分问题  
价值发生在需要被满足之时。人的需要有无穷的层次和形态，但只在特定条件下，满足他人需要可以交换金钱。以语言/思想为例，跟孩子说话，为孩子成长创造了价值；安慰一位朋友为朋友创造了价值；在知乎上分享人生智慧获得10K+点赞，这为很多人创造了价值。但是，以上都没有直接变现。而一位老师对孩子说话，可以卖钱；一位心理咨询师帮助一个患者，可以卖钱；专家出版专著，可以卖钱。浅显的原因是，后面的例子都做到专业化，但是进一步想想，为什么专业化就可以收费？是因为专业一定带来更大的价值吗？未必，一位糟糕的教师远不如一位有爱的家长；咨询师喋喋不休可能不如智者一句金言；专家的“砖业知识”更是误人不浅……博客和知乎上一些很好的文章，就是专业人士写出的，为什么此时他们的专业知识没有变现呢？  
原因在于，想要变现，你必须告诉人们你要变现。宣称的方法就是置身于市场。所谓职业，就是将自己的技能置于市场，别的什么都保证不了。市场为交换提供两个条件：一是心理条件，进入市场的人做好了付费准备；二是支付途径。
为什么你有知识却进不了市场呢？因为从一句话到一本书，从咖啡馆到大讲堂，价值可以发生在任意长度、任意时间和任意场景上——价值存在于连续谱上。而能换钱的可能只是一本书或企业讲座的形态——用于交换的价值是离散的。这是为什么我们读了很多书，却不能得到成正比的金钱，因为你的知识全在连续谱上，不具备离散性。离散性有两个特点，一是边界清晰，二是体量显著，从这个角度观察，“专业性”就是离散性。这可以解释为什么一些平庸的作者可以有很高的收入，虽然 ta 只有一桶水的价值，但是年复一年的重复，制造了十桶水的体量，并给读者以清晰的边界。  
所以，知识工作者想要知识直接变现，我认为首要的是修正自己的价值认识，改变知识应该免费分享的纯粹心理，宣称自己的知识有价，需要用金钱来换；同时改变知识只有非常完备才能卖钱的完美心理，在不触及道德的情况下大胆创作，进入市场。更充分的准备则是大体量地在同一主题下输出，并认识到，质量是第二位的，数量是第一位的，多则变。  
补充一点，群里话题讨论时，常见观点是知识没有转化为生产力，或者知识在转化生产力过程中没有知识工作者想象得那么重要。我完全同意这些观点，但是我这里特别关注的是，知识本身的价值。我认为这种思考更有普遍意义，首先，作为连续谱上的知识，不可能全部进入生产环节，知识的价值比生产价值更广泛；其次，即便是进入生产领域的知识，比如一个程序员的专业知识，从生产力转化的角度衡量，就是在特定公司里获得的工资；但是作为知识本身，却可能因为被传播而在无数的公司里转化为价值，那么，制造了这个知识的程序员，难道不应该为这个知识本身获得更高的收入吗？  
未来。可能读到第一段，大家就已经想到打赏、分答这一类机制。放在这里，是因为我认为它们不仅是现状，更代表了未来。打赏使人不仅可以为一本书买单，也可以为一篇文章买单；分答干脆让人可以为一句话买单。而人们真的愿意买单。这是在科技发展，社会富裕的背景下，极其便利的支付手段刚好与人们增强的付费意识、知识产权意识相结合的产物，这意味着一个泛化的市场正在出现。所谓泛化的市场，不同于传统市场只进行离散价值的交换，而是上演连续谱上的价值交换。凯文凯利说，未来，一个艺术家只要有200个粉丝就可以为生，对知识工作者亦如是。

**Comment by cp4** [comment]
张亚萨
金銭是最重要的资源嘛?  
~~ 
金钱不是，时间是

Zoom.ོQuiet
问题的相互关系, 其实都是三层次的:
认识金銭
运用金銭
创造金銭

以上问题都可以归到这几个层次中

乎乎 
知识有价，在让知识付费之前，先让人感觉知识价格是物有所值的。所以先积粉，而不是先收费。脑残粉付费无障碍，支付手段现在不是问题。在分答上是否可以出现，前期从无知名度的人却出现了高收入？如果不是刷单作弊的话。知识收费，合理，而且应该高，才行。前期就是获得大众信任。信任最值钱。信任是最重要的资源

Zoom.ོQuiet 
信任能用金钱购买嘛？
如果能…怎样的？
如果不能…广告公司乍生存的？

钱子游 
先来个世俗标准：信任无法用金钱买来。  
在来个我的想法：在当下金钱至上的社会，能对你给予金钱支持就是对你信任。

游民梁超 
这个感觉马哲差不多就说的挺好的，
金钱是价值的折现，
价值体现为满足需求，
所以金钱实质是满足各自需求的价值的流通工具，
换句话说，
得到金钱的过程实际是满足了某种需求后得到的流通性折现，

游民梁超 
然后好多人读书多觉得就应该能换很多金钱是很奇怪的，
因为很多时候的需求并不是知识，
知识多却并不实现需求当然也就无法折现

游民梁超 
这个可能是我们国家马哲教育我们价值取决于成本的说法误导了我们很多人罢

钱子游 
诚哥有云：知识并不决定财富的多少，但是知识越多，机会也越多。

钱子游 
知识并不决定你一生有财富增加，但是你的机会就更加多了。你创造机会才是更好的途径。——李嘉诚

斯羽 
@培炎 非常赞的整理，“一个艺术家有200粉丝就可以生存”，听起来很美好，可是要怎么实现

Zoom.ོQuiet 
''' “一个艺术家有200粉丝就可以生存”，听起来很美好，可是要怎么实现'''
那是 KK 曰的论断...
在互联网之前依靠邮寄可能实现,
现在基本不可能了...除非是 科学教 那种宗教管理形式,
否则,基本不可能维系粉丝忠诚的

Zoom.ོQuiet 
想想陈佩斯的经历就知道了, 艺术家的粉丝只有在本人死后, 才有忠诚度可言....

Zoom.ོQuiet 
反而是手工艺者, 比如那些高级西装氏家, 每个店, 每年就固定接受几个皇室的定单, 几百年传承下来, 技艺也越来越高....

Zoom.ོQuiet 
当然, 正如外国奢侈品的关联小厂的生存原则一样, 
绝对不和中国人合作, 以免被大规模生产冲杀, 
从而保卫每年小小的专门市场, 生存下来

朱常在
知识换钱的问题】交换，去哪里交换，交换什么？ ～你挖了一麻袋土豆，放在家里，但在外面逢人就说你家土豆多好，形容再恰当，比喻再贴切，远不如提到人眼前看。～以此，你提着麻袋沿街叫卖逢人便说“卖土豆”，偶尔有人光顾，很难长久维持，买家偶有夸赞，一夸你的土豆举世无双，你还当真，就呆在原地守株待兔么？不行，得去集市卖，货比三家，好东西自然有识货的人。找平台或自己建平台，找平台，不是你说了算，也不是土豆协会说了算，市场说了算，自己建平台，看本事。

朱常在
这个本事包括资本的力量也包括自身的力量……

朱常在
知识变现：1、卖培训。2、卖书。3、搞发明创造。4、运用知识在生活和工作中。其实4才是核心，直接变现（1、2、3）只有部分人可以，需要营销和团队。

朱常在
知乎是价值观产生，不是知识产生。因为知识是体系，知乎是碎片，大碎片

朱常在
END

斯羽
这样理解对吗？知识生产者的传统生存方式是被国家体制、贵族皇室供养？但是市场开启了一种新的可能

培炎
@斯羽 KK 的原文 https://site.douban.com/151743/widget/notes/7736184/note/210516404/ 数字记差了，但不重要。相对于艺术家需要铁杆粉丝，我觉得知识工作者不需要，艺术家改变风格、保持新鲜感极其难，但知识工作者可以不断选择主题，保持信息多样性

Zoom.ོQuiet
问题,这种知识产品, 一个搜索引擎就通用性的解决了

培炎 
举个栗子，[这篇文章]目前331人打赏，按最低额度5元计算，也收入了1500+，这样的知识能转化生产力吗？基本就是个趣味性，所以和艺术家的盈利方式本质相同，但无疑比艺术家灵活得多

**Comment by fengguang22** [comment]
知识变现，这四个字中间隐藏了两个字，信用。
知识工作者，真想把知识变现的话，要用知识变出信用来，信用是金钱的来源。
知识本身，留着自己用吧。

2016-07-26 15:39 GMT+08:00 Max Wang notifications@github.com:
