### ISSUE TITLE
[转型讨论][话题] 风险之难

### ISSUE THREAD

**Issue by cp4** [zoom-quiet/Noah2Ark#28]
- 怎样评估风险？  
- 风险怎样影响了你的决策？
- 你用什么样的决策应对风险？  
- 产业总有兴衰，人生一去不回，我们怎样面对变化？  
- 什么技能具有时间强韧性？ 
- 软技能是什么，软技能与硬技能到底谁更坚挺？
## DAMA-style
- 同一情景, 何时是风险何时是机会?为什么?
- 自己对风险的承受能力是多少? 如何衡量? 为什么?
- 应该保留多少资源来应对风险是合适的? 为什么?

**Comment by fengguang22** [comment]
每一条都是大问题，试着先开个头。
- 怎样评估风险？

> 改变大脑对风险的认知才能开启评估。通常在风险到来时我们的第一反应是否认。
- 风险怎样影响了你的决策？

> 不决策不会面对风险。
- 你用什么样的决策应对风险？

> 我想这里用“策略”替代“决策”更好。我了解过的最好的策略见于《Antifragile》这本书。简单说，是个哑铃策略——你需要一些主动暴露。
- 产业总有兴衰，人生一去不回，我们怎样面对变化？

> 做自己喜欢并且有能力去做的事情。
- 什么技能具有时间强韧性？

> 于个人来说，持续学习。
- 软技能是什么，软技能与硬技能到底谁更坚挺？

> 我想“软技能”是一个过于简单化地说法。例如我们常说沟通是软技能。如果你看过莱考夫的书之后，我想你会改变看法。
- 同一情景, 何时是风险何时是机会?为什么?

> 非常个人化的问题。每个人的判断基于他全部的历史，每个人的结果取决于偶然事件。
- 自己对风险的承受能力是多少? 如何衡量? 为什么?

> 你有没有练过举重？大脑和肌肉，两者成长的过程类似。
- 应该保留多少资源来应对风险是合适的? 为什么?

> 我们简单点儿说吧，越多越好，但是最好永远不要想着需要动用它们。

**Comment by cp4** [comment]
这个问题确实太大了，对风险的任何评估都是主观的，也许不应该评估风险有多大，而是风险有哪些？
@fengguang22 

> 不决策不会面对风险。  

这个不懂，不选择换工作就不会失业吗？应该怎么理解？  

> 于个人来说，持续学习。  

我觉得学习能力有点宽泛，一是学习能力能像某些技能一样持续提高吗？二是人一生有限，应对变化也不能总是从头学起呀，选择学什么不是更重要？  

> 简单说，是个哑铃策略——你需要一些主动暴露。  

哑铃策略和主动暴露的关系没懂……  
莱考夫还没看过，是《赖以生存的隐喻》那本吗？

**Comment by fengguang22** [comment]
“不选择换工作”和“选择换a工作或b工作”一样都是决策。更接近你的意思的表达我想是，“没想过换工作”，没想过怎么会觉得有风险？！就你提出问题的背景考虑，的确风险随时存在，做任何一个选择，或任何一种行动，都有一定的概率走得下去，也就意味着同时有一定的概率变差。

如果从行动出发，大概需要判断选择的概率是怎样，应该同时已经做好哪些后备以防不测，然后，为了让结果变得更好，需要补充什么，怎么获得，然后应用等等。我理解这个过程就是持续学习。这个过程中，可能发现需要补课数学和写作，可能发现体力更重要，可能就是要忍耐。。。理性总结我不知道怎么弄，但是到目前为止用户体验告诉我学习能力可以持续提高。

哑铃策略：好好工作（好好做正确的事情）＋一点儿冒险。简单地说，就是社会层级跃迁很难，本事和心态一点一滴积累都行，金钱则非常难，需要机遇。没有起色？没关系，活得长点儿，好好工作就是做得正确（多赢，老板，客户和同伴都好），时间一长，没发财也是赢家了。其实，发财还真没那么重要。

莱考夫的书一定要看。如果你对美国大选有兴趣，先去他的网站上看认知语言学的实际应用。他不支持共和党。

2016-07-26 15:53 GMT+08:00 Max Wang notifications@github.com:
