### ISSUE TITLE
中年职业安全引发的讨论

### ISSUE THREAD

**Issue by cp4** [zoom-quiet/Noah2Ark#29]
作者：纽约老李校长
链接：https://www.zhihu.com/question/26655174/answer/34759967
来源：知乎
著作权归作者所有，转载请联系作者获得授权。

就算是你有幸30岁时候还能被猎头找，那40岁呢？40岁的中层干部对资本家来说你的工资成本太高那时的你很危险的哟！如果你不是资本家或者高级大老板的嫡系，40岁万一遭遇职场政变被干掉怎么办？高不成低不就拖儿带女的更麻烦！

我举几个我看到的领导的例子：

我入职美的的第一任经理杨建涛，因为老乡关系他很照顾我，他算职场走的比较稳健的，现在还是美的湖北销售公司总经理。2015年辞职下海了。

我的第二任经理张崧，在美的郑州销售公司当了几年经理现在被美的干掉现在不知道人在哪里混饭吃。

第三任经理叫李欧，华凌冰箱成都中心经理，干了一年因为公司业务调整没了自己的岗位离开美的。

第三任美的经理郜书涛，湖南美的洗衣机的中心经理，当了2年还是3年的经理被美的干掉了，现在在半死不活的康佳洗衣机当经理。

当然美的这个血汗工厂起家的公司就这个臭毛病喜欢折腾人。

这四个老板，3个被美的在30多岁快到40岁时候干掉，职业生涯完全被打乱，一大把年纪了，到哪个公司你都不是嫡系，万一再干个两年把市场做好了上面又换人你又没了靠山再次被干掉，40多岁拖儿带女的你找谁哭诉呢？

联想比美的也好不了多少，我遇到三个上司，三个上司都辞职了。

我第一任领导俊哥在他35岁时候从重庆大客户总监岗位辞职，原因是遇到职业天花板知道在联想升不上去了，混吃等死也没意思。

我第二任领导40岁从联想辞职，原因是童夫尧把他从总监贬为普通销售，愤而辞职。

我以前重庆分公司的经理，联想内部整合，没了自己的位置，年薪100万的人呢，联想干了快一辈子了，说走还是要走。

**Comment by cp4** [comment]
熊猫• 秋 下午3:02
传说中的中年危机

徐梦阳 下午3:02
到哪都有饭吃

张亚萨 下午3:02
还是竞争力的问题吧

如斯 下午3:11
看是工作还是事业了。

如斯 下午3:11
工作到哪都可以做。

张亚萨 下午3:12
既然选择在市场一线的企业混，总要抗这个风险的 。生产力跟不上，被干掉就是真被动了

胡淼 下午3:13
问题好解决，早点做好自己的睡后收入方面的问题，早点财务自由

伊迭 下午3:16
财务自由，睡后收入
想到李笑来老师刚开了个付费专栏，名字就叫“通往财富自由之路”

如斯 下午3:19
如果基本生存有保障，其实财务自由要求不高

如斯 下午3:19
社会保障制度的完善。

爱喵Arthur 下午3:24
这方面国企可能好一些
怎么看待关于『外企消失的40岁-50岁年龄层』这个现象？
我不肯进体制内和家里争吵来争吵去，很大一部分就是因为他们担心我20年后的职业

游民梁超 下午3:26
不用担心，20年后机器人崛起，大家都失业

爱喵Arthur 下午3:26
我是严肃的……（

如斯 下午3:26
外企也要40-50的人当中层，哪来的消失。无非没关系或站错队了。

胡淼 下午3:26
先有睡后收入可以有更多的时间投入其他领域，可以赚的更多

游民梁超 下午3:29
我倾向于同意@伊迭 的意见，财富自由才是王道，不要依赖公司

伊迭 下午3:34
@游民梁超 是@胡淼 提出来的，我只是联想到了李笑来老师
谁都想实现财务自由……睡后收入是条路，想想怎么创造自己的睡后收入

发条橙子_2046 下午3:35
![xiaolaifreedom](https://cloud.githubusercontent.com/assets/1950286/17275279/91cb85fe-5734-11e6-8b5f-86653678b529.jpg)

如斯 下午3:39
提升时薪。

裘德 下午3:41
我自己是不相信机器人会怎样怎样的

胡淼 下午3:42
前期提升时薪+减低工时。中间找机会睡后收入

游民梁超 下午3:46
我推荐一本十多年前的老书《穷爸爸富爸爸》，这本书的思路着实影响了很多当今中国的中产阶级家庭

岳建博 下午3:47
小规模股权投资嚒？

伊迭 下午3:47
《穷爸爸富爸爸》也算是本知名度很高的畅销书了吧

游民梁超 下午3:49
是啊 罗伯特清崎还出过一款现金流游戏，我如今和朋友也老玩

张亚萨 下午3:50
桌游

岳建博 下午3:51
需要购买。正版挺贵的

游民梁超 下午3:51
桌游也有，ipad上也有这个游戏

游民梁超 下午3:51
玩过后就会填写个人资产负债表了

伊迭 下午3:53
桌游好啊，寓教于乐
给个关键词？

发条橙子_2046 下午3:54
@游民梁超 ipad上叫啥

蒋建国 下午3:54
…对于清崎财务状况不良的消息怎么看

游民梁超 下午3:54
就叫 穷爸爸富爸爸 现金流，我有一副，如果有北京的小伙伴的话倒是不介意一起面基

发条橙子_2046 下午3:54
我当时看完也想玩这个游戏

岳建博 下午3:54
@伊迭 现金流游戏

游民梁超 下午3:55
清崎那个财务不良是指部分公司财务不良罢，不良的话就破产掉就好了

伊迭 下午4:01
@岳建博 @游民梁超 谢谢
淘宝两百多三百一套[表情]

邱瑄 下午4:02
ios上有的

邱瑄 下午4:05
自己DIY一下啊 那个棋盘很简单 [偷笑]

岳建博 下午4:05
[表情][表情]我玩这个所谓出圈 基本都是股票投机

岳建博 下午4:08
20160723第14次游戏----------------------------------------------------------------
职业：经理
手上现金：500
非工资收入：6600

1.游戏目的
1.1实验出圈策略，提升量化能力，沉淀已有经验 ，觉察思维盲区 。

2.印象最深的投资
2.1冯剑峰与张威关于复合公寓的交易 
具体的量化的就不说了，这笔可以说是很典型的“多因素情景”交易模型，整理一下包括一下几个思考角度
2.11从量化角度，这笔交易可以使冯剑峰出圈，那么保证出圈的前提下他能提供的最大偿付金额是多少？先转让后交易，与先交易后转让，能提供的转让费分别是多少？
2.12从供需角度，是否有其它人能进行交易，自己对这比交易的期望是什么？主动权在谁手里？
2.13从情绪角度，是否建立了良好的谈判氛围，过去接触的经验如何？
2.14从综合博弈角度，自己和对方的目标是什么？倾向于合作还是竞争？
2.15从制定协议角度，协议是否具有可操作性还是仅仅只是画大饼？

2.2六万审计费
这笔意外之财一开始并没有引起我的特别重视，因为可重复性太低。后经田伟提醒，意识到其意义不在于游戏中是否能重复，而在于其本身“创造了规则”。现实生活的规则也是一样，但谁能发掘和创造新的规则，就能获得巨大的利益。

3.与现实的联系
3.1协议的可行性与交易的顺序会对合同执行产生巨大影响，生活中，能把合同细节想的越周到，就越能趋利避害。

4.收获与计划的改变
4.1根据规则（条件）确定合理目标，根据目标制定相应策略（指标），根据策略指导具体行动（决策）。
4.2模型
4.21交易的三个维度：
1）量化；2）供需（注意自己的目标）；3）干系人
4.22信息搜集与处理的三个层级：
1）固态信息（基本游戏信息：基本规则，卡片信息等）；2）动态信息（游戏状态信息：场上态势，供求关系，各玩家当前数据等，游戏时间与进程）；3）隐藏信息（玩家信息：游戏熟练度，价值偏好，情绪状态等）
4.23三种认知系统：
1）机械系统；
2）混沌系统 关键因素变化会对系统造成巨大影响；
3）复杂自适应系统 系统自动消解外来影响保证系统稳定；
4.3由4.2可见，想要做出正确的决策，想要获得好的结果，就要有耐心去理解复杂的问题，有能力处复杂的信息。越怕麻烦，就越不容易解决麻烦。

岳建博 下午4:09
这个是隔壁群的游戏总结

伊迭 下午4:12
赞，看起来好棒，看了更想玩了

游民梁超 下午4:13
罗伯特思路没错，但是投资标的物随着时代变化可能需要做适时调整哦

清荑 下午4:22
我想知道出圈后的投资策略，游戏里太简单了连锁店，工厂不停开

岳建博 下午4:23
出圈 基本上可以修一系工匠技能[表情] 享受生活

如斯 下午4:29
游戏 缺少了现实中的成本要素。

张亚萨 下午4:30
训练基本的投资概念

张亚萨 下午4:31
用来更好的理解方法论

牟琳 下午4:35
中年危机应该是真的。我的朋友圈估计五年就能开始进入危机了
现在就感觉到了忧虑
有的人搏一把创业。但是创业其实大部分人累死还是失败收场。投资，开公司，还有就是换公司换行业。这个问题是否存在看行业和企业性质了。公饭没问题，经验行也没问题
我觉得最好的办法是青春饭的行业，高收入第一桶金或者培养职业化的爱好，35前后能转换，也许比较理想
因为重度经验或者很稳定的行业普遍前期收入很低，如果不能财务自由或者为了让自己适当保持社会联系，转行是个不错的选择。

牟琳 下午4:39
青春饭行业收入高。年龄大了不是留得住与否的问题。很多人四五十混到中高层也一直做下去，但是个中甘苦自知，四十多拼的像二十多的，如果说为了钱和成就感，真的要很喜欢至少二者之一，还要有能力有机会才行，我感觉很多人的选择也是生活所迫不得不。

虚无刀 下午4:39
我也感觉到了[调皮]

安静 下午4:39
我准备在朋友圈卖珠宝

岳建博 下午4:40
还有就是赚钱后开小店子[表情]

牟琳 下午4:40
还要加一条有身体有命

虚无刀 下午4:40
@安静 从事珠宝行业的么？

虚无刀 下午4:40
我觉得身体好应该第一个

安静 下午4:41
no，闺蜜和他老公是。

牟琳 下午4:41
年轻能拼劳力拼劳力，够资本了岁数大了靠经验挂闲职。四五十岁高脑力，要有真爱和实力

安静 下午4:42
慢慢跟她了解下产品和行业，看以后可以开个实体店不。

牟琳 下午4:42
经营，小本经营。最多糊口，也辛苦。看能力运气了。年轻人该放手一搏。机关系统的又是一种活法

岳建博 下午4:42
还有就是二级市场

清荑 下午4:48
市场上的粮油店馒头店 肉店，水果摊一年也有二三十万，也是小本经营，一般是夫妻店

岳建博 下午4:49
还有就是类似于特许加盟 罗森之类的
你出钱铺面 他们铺货经营 分润[表情]

徐梦阳 下午4:50
开个711吧

岳建博 下午4:50
一般算投资回报还不错
关键是铺面资源很难找到

清荑 下午4:50
还真想开个711

岳建博 下午4:51
711好像在国内经营的不是很好 他家体验还是差了些 比

清荑 下午4:51
类似711的很多
青岛这边两三年功夫开遍了全城

如斯 下午4:52
可以网上卖水果。

徐梦阳 下午4:52
![mengyang](https://cloud.githubusercontent.com/assets/1950286/17275302/225cff1c-5735-11e6-84b8-3463e7a31b68.jpg)

徐梦阳 下午4:52
选好地方应该是能收回成本的

清荑 下午4:53
35万

安静 下午4:53
老公同事曾经在深圳开了三家绝味鸭脖店，月纯利润少的有1万多，多的三万多，老公全职管店，老婆上班。他们是最早在深圳买房的，然后几年后周黑鸭来了，他们把店全关了。把房也卖了，几百万全部投入了老家的高利贷，结果钱回不来了，房价涨了。

**Comment by cp4** [comment]
岳建博 下午4:54
[表情]相信我 如果小白的话 很难找到好铺面

清荑 下午4:54
绝味在开发区这边还不多，不过味儿太大了，最好雇人做，自己待一天要呛死了

岳建博 下午4:55
基本上好的铺面不公开流通[表情]

安静 下午4:55
货都是去拿的

清荑 下午4:56
可以赌一赌新售的空租的新入住小区底商，回迁户的话很快就住满了

安静 下午4:56
感觉深圳有很多小卖部c-store之类的都是请人看店的，自己投资。

清荑 下午4:57
撑住前两年后面人越来越满

岳建博 下午4:57
嗯 一般模式都是托管给连锁企业[表情] 我们目前就是管理这些东西

岳建博 下午4:58
餐饮零售没有办法讲很好的概念 没有大投资 都是个人小投资 但几百家还是蛮恐怖的

黎路遥 下午9:02
《穷爸爸富爸爸》的作者破产了。。 不由得想起一位长者语重心长的教诲：一个人的命运，当然要靠自我奋斗……

黎路遥 下午9:04
德鲁克的《自我管理》有提到中年危机，培养职业化的兴趣/第二事业/平行事业，是他提到的一个解决方案。

岳建博 下午9:05
@黎路遥 应该是公司破产[微笑]

—————  2016-7-31  —————

Carolyn 上午11:30
上面在讲中年危机、财务自由、平行职业的话题，我最近在看炒房的水库论坛，倒是很洗三观。

Carolyn 上午11:37
只有大城市才有房地产，谨慎购买二线城市的房子，三线以下没有金融属性。首付三成，利用一切杠杆贷款，有人不惜假结婚拿到京沪房票，学区房不能碰。炒房的流派，温州人是送钱的人形ATM，别买CEO盘和新兴区域品牌房，寻找笋盘，突破屌丝的初房情结。

Carolyn 上午11:40
[水库文章目录 : http://mp.weixin.qq.com/s?__biz=MzAxNTMxMTc0MA==&mid=206663049&idx=1&sn=b811130f28a5a8fd49fbd8204b90eb72&scene=1&srcid=0731nnu2QFchpwFAfgD32PmE#rd]
具体看他公号或者去水库论坛

Carolyn 上午11:44
看论坛有人去年购入厦门岛外一套房166万，今年转手270万，深感房地产市场才是吸收增发货币的大海绵，辛辛苦苦做点实业、经营收入，和地产比有量级上的差异

mind 上午11:48
啥叫笋盘

Camus 上午11:48
北京亦如此深圳亦如此

邱瑄 上午11:50
如雨后春笋

Carolyn 上午11:50
被严重低估的房子吧

Carolyn 上午11:50
北京要有房票，深圳价格有钱可以炒

游民梁超 上午11:50
毕竟北京户口比美国绿卡难拿。。

mind 上午11:51
有钱北京户口才有用……

mind 上午11:52
估计快积分啦吧

Carolyn 上午11:52
有美国绿卡也限购，外国人在中国只能买一套自住房吧

Carolyn 上午11:53
所以有人让有户口的人代买啊，付房票钱，风险很高就是了

mind 上午11:54
@Carolyn 这个风险很高，房产证也是代买人的名字

尹珺cherryPotter 上午11:55
那就等一段时间就ok了吧

Carolyn 上午11:55
是啊，他们怎么控制风险就不知道了，财帛动人心

尹珺cherryPotter 上午11:55
没有北京户口不一定不能买房

mind 上午11:56
纳税五年

Carolyn 上午11:56
商住房不要买，没升值潜力

邱瑄 上午11:56
温州人不是常说 富贵险中求吗

mind 上午11:56
那买啥

Carolyn 上午11:57
看流派啊

Carolyn 上午11:57
老破小、法拍房等等

Carolyn 上午11:59
温州师奶团就是他们炒房客眼中的接盘侠

邱瑄 下午12:00
有数据流吗

Carolyn 下午12:01
看论坛吧@邱瑄 

Carolyn 下午12:02
还有一个米课网的暗夜课程，也是关于炒房，讲师也是混水库论坛的

达ོ达ོ在简单 下午12:11
老破小、法拍房等等 ，然 。早几年就认识此中高手 ，但资源就被那几个人掌握着，旁人无从入手

Carolyn 下午12:13
老破小可能可以学学，法拍房、药单房估计是玩不了，民宿房有心力的人可以做

Carolyn 下午12:17
其实，改装民宿也算小本经营的一种了

游民梁超 下午12:18
改成airbnb

安静 下午3:00
朋友之前是两房。去年买了，夫妻假离婚买了个双拼，月供两万多，还剩几十万在手里。不到一年涨了200万

Carolyn 下午3:20
这种就是打定主意炒房的，假离婚都干，月供2万运转下应该有渠道解决，并不是自主背贷款30年。这么短的期限，哪怕刷信用卡，或者借高利贷，和利润比起来都不算什么。

**Comment by fengguang22** [comment]
我觉得，大体上，能更好的人也是到了中年才成熟，老想着中年危机，不是自找没趣吗？！
好不了的，就不用到中年了早已危机重重。

2016-07-31 15:44 GMT+08:00 Max Wang notifications@github.com:
