### ISSUE TITLE
邮件列表欢迎围观.

### ISSUE THREAD

**Issue by YixuanFranco** [zoom-quiet/Noah2Ark#30]
## 背景

之前在一个群里每天推 TED, 
推了半年, 大概积累了 100+ 个 ted 文字版.
## 起因

大妈倡议, 如果有人愿意看的, 可以申请加入邮件列表. 
地址: [邮件列表](https://groups.google.com/forum/#!forum/xbyct)
其实不申请加入现在也是公开的, 大家可以随意看.

然后想加入的可以尝试手动加入一下, 加不了的可以留 gmail/or 其他邮箱, 我把你拉进去.
## 那个...

因为为了解放微信吗...所以邮件列表可以是主要玩法. 
咱们有兴趣的可以试试...
以后在邮件列表里玩 主题圆桌会谈 也挺有意思的.

**Comment by ZoomQuiet** [comment]
嗯哼,  班长理解反了: ANN 方舟系资源关系 · Issue #1 · zoom-quiet/Noah2Ark 
    https://github.com/zoom-quiet/Noah2Ark/issues/1

就是作这事儿的, 只是, 原本是指派 班长 作管理员手工将大家在 #1 提出邮箱的都
批量直接订阅上列表, 以免进行一次额外的翻越和学习操作.

所以, 这个 issue 也是失效的了,继续在  #1  收集操作就好 ;-)
CANCEL for overflow ;-( 放弃/转义/过期....

**Comment by YixuanFranco** [comment]
-_- 日落西山红霞飞，才懂大妈心思归，心思归...

**Comment by Aaron-jun** [comment]
邮件列表我好像打不开，请求帮忙把邮箱带上：shaojunhuang@outlook.com。谢谢！(黄少君)
