### ISSUE TITLE
[正念学习] 结束

### ISSUE THREAD

**Issue by cp4** [zoom-quiet/Noah2Ark#48]
## 招募

九月好！  
金秋气燥，木叶凋零，天地为之一变。你的心情舒畅爽朗，还是凄郁黯然？你在为工作焦虑，还是为情感纠结？也许你需要一次郊游，归来后的城市却更难忍受；也许你想写一首诗，环顾格子间找不到一丝灵感。如果缺少自我省察，改变就多一分盲目；如果不能擦掉眼中积习，远方永远只在远方……   

正念，源于东方带有神秘色彩的修行实践，正被越来越多人认识，已经被用于心理治疗，成为积极心理学的组成部分。如果你希望改善自我认知，如果你渴望控制负面情绪，如果你想更新对学习、创作、关系等种种日常体验，欢迎参加本次活动。  
# 子群招募# 正念——了解

招募时段：[9.1 - 9.3]  
活动时段：[9.6 - 9.19]  
本次招募面向正念学习初始阶段 —— “了解”，跨度两周。两周后，会面向下一阶段，在参加者中进行第二次招募。  
不同于以往，活动交流内容不对外发布，预期活动输出:一页体验书单。  

参考书单：  
@刘建鸿 [积极心理学读本](https://www.douban.com/doulist/162710/?start=50&sort=seq&sub_type=)  
@TonyYet [mindfulness](https://www.douban.com/doulist/1479208/)  
@刘未鹏 [正念的科学与艺术](https://www.douban.com/doulist/1823403/)  

Wake Me Up, When September Ends.

**Comment by cp4** [comment]
## 活动规则

首先，每个成员必须准备：不超过两本正念相关书籍。  
**注意，请通过自己的能力甄别、选择指导书籍，禁止在群里荐书或询问。目的是避免从众效应，使大家学习来源趋于单一。**      

请于9月5日午夜前，邮件告知我如下信息：1. 你的基本情况（以前参加活动介绍过的就不用写了）；2. 学习正念的目的；3. 你选择的书籍。我会依据这些信息对大家分组。
_分组的目的是为了控制人数，保证交流质量。_  
_请大家使用邮件的目的是，我能知道每个人的邮箱，在整理交流记录后，我会把相关文档邮件发送给大家。_    

这两周的活动分为两个步骤，需要每人做两次分享。  
第一个七天：进行第一个步骤，请每人分享如下内容：  
1. 自我介绍
2. 我想达到什么目标。比如：我想解决失眠或抑郁问题，或者：我想突破习惯思维，更有效地学习或创作  
分享后，听者根据自己的经验和知识给出建议，讲者综合自己的思考、书中的指导、大家的建议，进行自主练习。
第二个七天：进行第二个步骤，请每人分享如下内容：  
1. 这一周以来，我采用了怎样的练习方式  
2. 执行情况如何  
3. 效果如何  
4. 我使用的书籍，需要对书籍进行体系概括，综合评价，以及哪些点对我触动和改变最大   

_第一次分享鼓励丰满的自我介绍，以增进了解互信，如有过打坐等相关经历，建议分享，这对初次接触者会很有价值。_
_大家无需对分享有压力，长话长说，短话短说即可，分享的时间长度以相互交流为主。_

其他时间，大家可任意交流，包括且不限于：读书笔记(鼓励多输出，使没有看过这本书的人能读到书中精华，但在自己第二次分享之前不许暴露书名)，练习中的体验，心得，问题。

**Comment by cp4** [comment]
第一阶段报名 23 人，最终参加活动 19 人。
连带发起人共 20 人，分成 4 个小组
- ATT
- AWR
- ACQ
- AWK  

第一阶段于 9.20 结束，在群内组织第二阶段招募。

**Comment by cp4** [comment]
## 第二阶段招募

大家好，正念学习第二阶段的招募正式开始。       

正念不但有令人神往的深入空间，更是日常生活的得力帮手。很多朋友说，两周时间太短。现在，经历了初步了解，你是否想继续深入？是否对进一步学习有新的打算？  
学习到了第三周、第四周，往往会进入倦怠期。最初的感动消失、行动不见成效、生活复归常态、再一次失望而返，只不过，又玩过一个花样而已…… 所以，第二阶段招募在第二周之后，既是一次重新选择，又是一次重整旗鼓。我的信念是，不管有没有效果，坚持练完两个月再说！  

第二阶段时间周期——九周。  
活动时间：[9.24 - 11.25]  
活动方式：  
- 找小伙伴结对打卡。不结对亦可。  
- 每两周进行一次碰头会，交流形式：有时间证据的记录，如，与打卡小伙伴微信对话记录或日志（未结对者），以链接方式提交。时间安排在两周后的下一周。比如：  
  前两周是9.24-10.7，碰头会安排在10.8-10.14这一周前两天（天数视人数调整），以此类推。  
  因时间周期长，简便为要，碰头会不约定同场进行。  
  未提供近两周学习记录者，出局。  
- 其他时间随意提问、分享。  

报名方式：  
- 邮件说明：这两个月我的学习计划
- 报名时间：[9.21-9.23]  

结对与分组：  
- 视报名人数确定是否分组（请尽可能详尽告诉我学习计划和学习素材）  
- 活动在组内进行  
- 结对在组内公开进行

**Comment by cp4** [comment]
参加第二阶段学习者共 15 人（包括发起人）。  
后续情况暂停更新。

**Comment by cp4** [comment]
第二阶段活动于 11 月 27 日结束。  
最后一周的总结分享，参加者 6 人。

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
