### ISSUE TITLE
法语电影清单20160901

### ISSUE THREAD

**Issue by aJiea** [zoom-quiet/Noah2Ark#49]
### 法语电影清单20160901项目日记

Noah's Ark群的一个惊喜是，每次打开不知道会邂逅什么主题。那么我想，这种小众的电影主题是不是也可以开issue，吸引一批人的同时做自己的持续输出。
昨天计划做法语电影清单，外网和国内都是空白。今天着手开干，法语喜剧有名，法式幽默中可以看出人们生活态度和社会百态。

今日汇总：
- 重新启动珠海法语群 Francophonie de ZHUHAI，为不同层次法语爱好者提供有用内容谈资。如，初级可以了解有名演员，电影分类；中级可以看电影学法语，同法国人谈到哪些演员才会接地气；高级可以讨论电影背后话题
- 发起【活动】
  1. 建议初级法语爱好者先看看我笔记脑图电影的分类有哪些，可以进行补全 
  2. 中级学习者可以根据演员名字和电影名字自行查询相关信息，并在简书上沉淀下来，在群内分享
  3. 看电影能够看懂80%无字幕的，欢迎同我一起看~
     >【玩法】大家可以把这个当成一个集中训练，如果你们在简书上写下自己的学习笔记，我会建立一个专栏收录大家的学习笔记，并邀请法语大牛给你们做修改和评论~
- 列出目录清单涵盖：喜剧，动画，小生活，恐怖等系列。列出喜剧里KOL名单，分为已故老演员和当代演员。做出老演员里MVP最小清单5人，排期观影，为能更好介绍法国电影

![20160901](https://cloud.githubusercontent.com/assets/13810631/18176273/79cdd56a-70a7-11e6-8c0c-23fe93b38e1b.png)
- 记录项目日记：Github，[简书](http://www.jianshu.com/p/f964b912b952)，微信群
- 所用工具：Scrivener， Mindjet，IMDB

<img width="899" alt="scrivener" src="https://cloud.githubusercontent.com/assets/13810631/18176324/b5b5b476-70a7-11e6-9959-9ae262ced8f2.png">

**Comment by ZoomQuiet** [comment]
supper!
严正期待!
aJiea 总是能高速 got 到俺吼过的要点并立即上身理解,并执行起来...

2016-09-01 11:54 GMT-05:00 aJiea notifications@github.com:

> Noah's
> Ark群的一个惊喜是，每次打开不知道会邂逅什么主题。那么我想，这种小众的电影主题是不是也可以开issue，吸引一批人的同时做自己的持续输出。
> 昨天计划做法语电影清单，外网和国内都是空白。今天着手开干，法语喜剧有名，法式幽默中可以看出人们生活态度和社会百态。

...

**Comment by arlmy** [comment]
虽然不会法语，但是看过些发法语电影，梳理片单能帮忙

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
